### PR TITLE
Massive Update for Laravel 8.x

### PR DESCRIPTION
**Pull request by ghost**
I've made some various changes to the package to allow for more modification and ease of access to vendor files. I've also updated the code for most of the blade files and php files up to industry standard Laravel 8.x coding practices.

### Changes

- Removed almost all assets from the public folder except for the JS files and the demo files. All assets should now be in `/resources`. CSS files are now managed via the Laravel Mix SASS compiler, with exception to the Right To Left (RTL) file, which is copied verbatim to `public` folder.
- Moved the images in the package to the storage folder. The user will have to create a symlink using the `php artisan storage:link` command.
- Updated all the `active` css classes to use the current route by name. i.e. `Route::currentRouteName()` instead of the `$activePage` variable which sometimes has the habit of breaking on the `/profile` page.
- Added a new function in the `MaterialPreset.php` file to replace the `static::updateAssets()` function. The new function `static::updateWebpackMixJS()` will take care of many of the file moves and changes needed for this update.
- Added a function in `MaterialPresetServiceProvider.php` file to handle publishing of assets into their appropriate folders. This can be used by the `php artisan vendor:publish --provider="LaravelFrontendPresets\MaterialPreset\MaterialPresetServiceProvider"` command.
- Added all the SASS files into the package for easier manipulation of the specific modules of the package.
- Removed the Laravel < 5.5 Installation instructions as the `laravel/ui` package was released after 5.5, and this package is not actively compatible with < 5.5. If a user is still running Laravel < 5.5, then they should be forced to update their Laravel version to the industry standard 8.x (at the time of writing this pull request).

### New Installation Instructions

1. CD into your Laravel application
2. Run the following command to install the default laravel authentication scaffolding: `composer require laravel/ui && php artisan ui vue --auth`
3. Run `npm install && npm run dev` to build the package. If your Laravel app is a fresh install you will have to run `npm run dev` twice.
4. Install the Material Admin Dashboard by running the following Composer command. `composer require laravel-frontend-presets/material-dashboard`. Registering the service provider is now handled automatically as of Laravel 5.5 via Composers PSR4 autoloading.
5. Run `php artisan ui material && php artisan vendor:publish --provider="LaravelFrontendPresets\MaterialPreset\MaterialPresetServiceProvider"` to publish and install the Material Admin Dashboard files to their appropriate folders. Note: Make sure to clean up the routes/web.php file as sometimes the package duplicates entries for `Auth::routes()` and the `/home` route. This almost always happen so make sure to pay special attention to this.
6. Run `composer dump-autoload`
7. Migrate the necessary database files by running `php artisan migrate`. If you wish to seed your database with the temporary users entries, use the `--seed` flag.

### CODE REVIEW

**Comment by teamupdivision** [comment]
Hello and thanks for the PR and recommendations.
We will evaluate and follow up on this thread.

All the best

**Comment by finnie2006** [comment]
any update on this? @teamupdivision

**Comment by teamupdivision** [comment]
Hi @finnie2006,

Thank you for your message and contribution. Unfortunately, we will not be merging this PR for the moment.

Best,
UPDIVISION Team

**Comment by finnie2006** [comment]
Why not?

**Comment by teamupdivision** [comment]
Thank you again for your contribution. For the near future, we already planned to introduce a set of optimizations that will cover these aspects too. For this reason, we were not able to merge this at this moment.

**Pull request closed without merging**
